### ISSUE TITLE
Visual Studio 2017 support

### ISSUE THREAD

**Issue by zgabi** [bennor/AutoT4#17]
Please add Visual Studio 2017 support

**Comment by bennor** [comment]
Will have a look at it this weekend.

**Comment by zgabi** [comment]
Any news on this task?

**Comment by bennor** [comment]
Sorry. Haven't had time to look at it yet but will definitely get to it this week.

**Comment by bennor** [comment]
VS 2017 support is up in the gallery now. Or grab the VSIX from the [release](https://github.com/bennor/AutoT4/releases/tag/v1.2.1).

**Comment by zgabi** [comment]
Thank you very much.

**Comment by bennor** [comment]
No problem. Sorry it took me so long. 😃
