### ISSUE TITLE
How to specify which TT files to run. I.e. exclude TT files from being AutoTransformed

### ISSUE THREAD

**Issue by VagyokC4** [bennor/AutoT4#4]
This tool works (only too well).  I've tried others that throw an error trying to transform my TT files.

However, I need to be able to specify which files should be Transformed so that this tool doesn't blanket transform all my TT files upon build.

One suggestion would be to check the 'Build Action' on the TT file, and only transform if it is set to 'None' this way I could selectively set the TT files I don't want transformed to 'Content' and have them skipped.

**Comment by VagyokC4** [comment]
Created a Pull Request for this functionality: https://github.com/bennor/AutoT4/pull/5

**Comment by bennor** [comment]
This is a creative approach, but I feel like setting them to `Content` (meaning they'll be included in the build output) is a little bit hacky. I've nearly finished the other approach, so I will get that live by Saturday. (I will try for earlier if I get time.)

**Comment by VagyokC4** [comment]
+1

**Comment by bennor** [comment]
Will do. (I may have already done that too.)
