### ISSUE TITLE
Will you be making this available for Visual Studio 2015 anytime soon?

### ISSUE THREAD

**Issue by VagyokC4** [bennor/AutoT4#9]
Will you be making this available for Visual Studio 2015 anytime soon?

**Comment by bennor** [comment]
Will try to get to it this weekend. :)

**Comment by bennor** [comment]
Hey @VagyokC4 - I haven't had time to have a proper look at this yet. It's actually been added (it's just a manifest change), but there's a bug in the latest version I haven't been able to fix yet. (It causes VS to crash, and it crashes so hard I can't get it to hit a breakpoint on the error.) 

If you want to try it out, it's in the pre-release for [v1.1.0](https://github.com/bennor/AutoT4/releases/tag/v1.1.0). You might have more luck with it than I have.

**Comment by VagyokC4** [comment]
@bennor Anything a 'try' 'catch' couldn't fix?

**Comment by bennor** [comment]
Unfortunately not that simple. There are a few catches in there already.

**Comment by bennor** [comment]
The latest release should work, and has the additional option to change the default from "Before build" to "After  build" or "Disabled".

https://github.com/bennor/AutoT4/releases/tag/v1.2.0

**Comment by bennor** [comment]
There's VS 2015 support in the latest release, which is tracked in #3.

**Comment by pwhe23** [comment]
Great extension, glad to hear there is 2015 support! I landed here because the VS Gallery doesn't mention the VS 2015 support, you might want to update it when you get a chance so others don't get confused.

**Comment by bennor** [comment]
Thanks @pwhe23, I've updated it today.

**Comment by pwhe23** [comment]
You rock!
